/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class UI_XYGraph */

#ifndef _Included_UI_XYGraph
#define _Included_UI_XYGraph
#ifdef __cplusplus
extern "C" {
#endif
#undef UI_XYGraph_FOCUS_TRAVERSABLE_UNKNOWN
#define UI_XYGraph_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef UI_XYGraph_FOCUS_TRAVERSABLE_DEFAULT
#define UI_XYGraph_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef UI_XYGraph_FOCUS_TRAVERSABLE_SET
#define UI_XYGraph_FOCUS_TRAVERSABLE_SET 2L
#undef UI_XYGraph_TOP_ALIGNMENT
#define UI_XYGraph_TOP_ALIGNMENT 0.0f
#undef UI_XYGraph_CENTER_ALIGNMENT
#define UI_XYGraph_CENTER_ALIGNMENT 0.5f
#undef UI_XYGraph_BOTTOM_ALIGNMENT
#define UI_XYGraph_BOTTOM_ALIGNMENT 1.0f
#undef UI_XYGraph_LEFT_ALIGNMENT
#define UI_XYGraph_LEFT_ALIGNMENT 0.0f
#undef UI_XYGraph_RIGHT_ALIGNMENT
#define UI_XYGraph_RIGHT_ALIGNMENT 1.0f
#undef UI_XYGraph_serialVersionUID
#define UI_XYGraph_serialVersionUID -7644114512714619750i64
#undef UI_XYGraph_serialVersionUID
#define UI_XYGraph_serialVersionUID -2284879212465893870i64
/*
 * Class:     UI_XYGraph
 * Method:    calculateSizeOfPointY
 * Signature: (DI)D
 */
JNIEXPORT jdouble JNICALL Java_UI_XYGraph_calculateSizeOfPointY
  (JNIEnv *, jobject, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
